apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-engine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-engine
    spec:
      containers:
      - name: api-engine
        image: hyperledger/cello-api-engine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-engine-config
        env:
        - name: DEBUG
          value: "True"
        volumeMounts:
        - name: api-engine
          mountPath: /var/www/server
        - name: media
          mountPath: /var/www/media
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: api-engine
        hostPath:
          path: /opt/lampp/htdocs/start/cello/src/api-engine
      - name: media
        hostPath:
          path: /opt/cello/api-engine/media
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
