apiVersion: v1
kind: Service
metadata:
  name: api-engine
  labels:
    app: api-engine
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: uwsgi
  selector:
    app: api-engine
