apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis